const boxes = [
    {
      id: 001,
      categoria: "Categoria01",
      destacado: true,
      nombre: "Product001",
      precio: 560.0,
      precioAnterior: 620.0,
      imagen: "../assets/img/product001.jpg",
      medidas: "15 x 15 x 10 cm",
      peso: 3.2,
      personas: 4,
      numpiezas: 8,
      piezas: [
        "pieza01",
        "pieza02",
        "pieza03",
        "pieza04",
        "pieza05",
        "pieza06"
      ],
      sabores: [
        "sabor01",
        "sabor02",
        "sabor03",
        "sabor04",
        "sabor05",
      ],
    },
    {
      id: 002,
      categoria: "Categoria01",
      destacado: false,
      nombre: "Product002",
      precio: 940.5,
      precioAnterior: 1020.0,
      imagen: "../assets/img/product002.jpg",
      medidas: "15 x 15 x 10 cm",
      peso: 3.2,
      personas: 4,
      numpiezas: 8,
      piezas: [
        "pieza01",
        "pieza02",
        "pieza03",
        "pieza04",
        "pieza05",
        "pieza06"
      ],
      sabores: [
        "sabor01",
        "sabor02",
        "sabor03",
        "sabor04",
        "sabor05",
      ],
    },
    {
      id: 003,
      categoria: "Categoria02",
      destacado: true,
      nombre: "Product003",
      precio: 320.0,
      precioAnterior: 420.0,
      imagen: "../assets/img/product003.jpg",
      medidas: "15 x 15 x 10 cm",
      peso: 3.2,
      personas: 4,
      numpiezas: 8,
      piezas: [
        "pieza01",
        "pieza02",
        "pieza03",
        "pieza04",
        "pieza05",
        "pieza06"
      ],
      sabores: [
        "sabor01",
        "sabor02",
        "sabor03",
        "sabor04",
        "sabor05",
      ],
    },
    {
      id: 004,
      categoria: "Categoria02",
      destacado: false,
      nombre: "Product004",
      precio: 450.0,
      precioAnterior: 620.0,
      imagen: "../assets/img/product004.jpg",
      medidas: "15 x 15 x 10 cm",
      peso: 3.2,
      personas: 4,
      numpiezas: 8,
      piezas: [
        "pieza01",
        "pieza02",
        "pieza03",
        "pieza04",
        "pieza05",
        "pieza06"
      ],
      sabores: [
        "sabor01",
        "sabor02",
        "sabor03",
        "sabor04",
        "sabor05",
      ],
    },
    {
      id: 005,
      categoria: "Categoria03",
      destacado: true,
      nombre: "Product005",
      precio: 500.0,
      precioAnterior: 620.0,
      imagen: "../assets/img/product005.jpg",
      medidas: "15 x 15 x 10 cm",
      peso: 3.2,
      personas: 4,
      numpiezas: 8,
      piezas: [
        "pieza01",
        "pieza02",
        "pieza03",
        "pieza04",
        "pieza05",
        "pieza06"
      ],
      sabores: [
        "sabor01",
        "sabor02",
        "sabor03",
        "sabor04",
        "sabor05",
      ],
    },
    {
      id: 006,
      categoria: "Categoria04",
      destacado: true,
      nombre: "Product006",
      precio: 1028.0,
      precioAnterior: 1320.0,
      imagen: "../assets/img/product006.jpg",
      medidas: "15 x 15 x 10 cm",
      peso: 3.2,
      personas: 4,
      numpiezas: 8,
      piezas: [
        "pieza01",
        "pieza02",
        "pieza03",
        "pieza04",
        "pieza05",
        "pieza06"
      ],
      sabores: [
        "sabor01",
        "sabor02",
        "sabor03",
        "sabor04",
        "sabor05",
      ],
    },
  ];
